### ISSUE TITLE
Workflow on PRs not starting run

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/eclipse-tractusx.github.io#1070]
### Current Behavior

The github action "Build and deploy to GitHub Pages" currently doesn't run on Pull Requests and remains in state "Expected - waiting for status to be reported". This blocks merging approved PRs as visible below:

![image](https://github.com/user-attachments/assets/7bb2069d-636b-46c5-b4e1-d4471af39704)

### Expected Behavior
Action runs. Produces success or error.

### Steps To Reproduce
Open a PR or take a look at #1069, #1064, #1061 or a couple other ones that are open right now. 

Important technical details: 
Might have something to do with branch protection rules like [here](https://github.com/orgs/community/discussions/26698#discussioncomment-3252954)

**Comment by stephanbcbauer** [comment]
thx @arnoweiss -> @matbmoser do you remember where we changed the protection rule?

**Comment by stephanbcbauer** [comment]
mh i think there was a missunderstanding by activating [this](https://github.com/eclipse-tractusx/.eclipsefdn/commit/d71a69a053f340b9b0c3217e41784e8cb61c0089#diff-04d4171c51c6603bee04b7b16812ef6a5bab0305827076085c9280340da2a687R321)  cause as i remember (but not 100 % sure) this action is executed after merge, but merge is now blocked because of this check, which gets never green?

@matbmoser @arnoweiss

**Comment by stephanbcbauer** [comment]
> That sounds like accurate analysis. @matbmoser - can you prep a PR for this?

should be fixed by https://github.com/eclipse-tractusx/.eclipsefdn/pull/108

**Comment by arnoweiss** [comment]
thanks for the fix!
