### ISSUE TITLE
Change linked .md file from menu item "versions"

### ISSUE THREAD

**Issue by danielmiehle** [eclipse-tractusx/eclipse-tractusx.github.io#167]
1.) Please link the following .md file to the main menu item "versions"
https://github.com/eclipse-tractusx/tractus-x-release/blob/main/CHANGELOG.md

2.) Please delete the old .md file afterwads
 https://eclipse-tractusx.github.io/versions/

**Comment by FaGru3n** [comment]
was solved by @santiagoejm  in #170 
to 1.) for now you can use the following link https://eclipse-tractusx.github.io/CHANGELOG

to 2.) https://eclipse-tractusx.github.io/versions/ is not available anymore 

@danielmiehle  because you already merged it would assume that this issue is obsolete for now, will close it
