### ISSUE TITLE
Make path for source md-files configurable

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/eclipse-tractusx.github.io#277]
Currently, the webpage content is built exclusively from the `docs-kits_versioned_docs/version-3.1.0`. Yet, the development of new KITs takes place in the `docs-kits` folder. In order to test my setup locally, everything has to be in the version 3.1.0 Folder and then move over to `docs-kits` before a PR. 

Also, the documentation still states that the KITs live in `docs/kits`. This is outdated and should be updated as well.

**Comment by santiagoejm** [comment]
Hi @arnoweiss, you are right about the outdated documentation, but while that is been updated let me help with your enquiry.  Actually the `docs-kits` folder is pointing to the `Next` version, is in here where you can see your modifications, so you don't need to worry or make your development in the `kits_versioned_docs/version-3.1.0`, you can/must work directly in the `docs-kits` folder, because in the future when a new release is made, the content of the `new version` is gonna be a copy of the state at the moment of the `docs-kits` folder. That is how `Docusaurus` handles the `versioning`, hope it makes sense.

There is a `dropdown` menu that only displays when in the KITs documentation at the top-right corner:
<img width="1765" alt="Screenshot 2023-06-26 at 18 26 59" src="https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/68547995/8ccfd682-c186-4135-96db-b1fa9537dddc">
When you go to `Next`your changes should be visible, don't forget to update the `sidebarsDocsKits.js` if needed.

**Comment by arnoweiss** [comment]
Thanks for the hint!
