### ISSUE TITLE
Use of specificAssetIds in Traceability Kit

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/eclipse-tractusx.github.io#300]
In the Traceability Kit, the examples encourage use of "specificAssetIds" in a way that is incompliant with the Asset Administration Shell Specification. [Here](https://eclipse-tractusx.github.io/docs-kits/kits/Traceability%20Kit/Software%20Development%20View/Specification%20Traceability%20Kit#lookup-up-a-digital-twin-with-local-ids), the following example is made:

```json
[
  {
    "key": "manufacturerId",
    "value": "BPNL7588787849VQ"
  },
  {
    "key": "manufacturerPartId",
    "value": "95657362-83"
  },
  {
    "key": "partInstanceId",
    "value": "NO-574868639429552535768526"
  }
]
```
These IDs clearly describe separate things: a `manufacturerId` describes a manufacturer, a `manufacturerPartId` descibes a part/asset. The[ AAS-specification](https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf) (p. 60) states on specificAssetIds: 

_"Additional domain-specific, typically proprietary identifier **for the asset** like serial number, manufacturer part ID, customer part IDs, etc"_

If the manufacturer Id must be included, that should be either in the externalSubjectId within a specificAssetId or in the submodel payload itself - I think.

**Comment by markuskeidl** [comment]
Currently, building data chains with Traceability relies on this - without it, Traceability would not work. We talked about this with Birgit Boss, but there seems to be no other solution (better solution) how to use composite keys to look for digital twins. Just a serial number is not enough as it is not unique outside of a company.

It's like that already since before release 3.0. 

I understand what you mean and I also agree that these three entries are not keys identifying the asset on their own, but without another solution how to handle composite keys, we are stuck with this approach.

**Comment by arnoweiss** [comment]
It'd be cleaner if these identifier-segments were aggregated into one. But I understand that this is functionally necessary and thus "dogmatic" considerations like this shall not break running code.
