### ISSUE TITLE
PR #354 prevents webseite build

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/eclipse-tractusx.github.io#360]
Pullrequest #354 prevents website build:

```shell
> eclipse-tractusx-github-io@0.0.0 build
> docusaurus build

[INFO] [en] Creating an optimized production build...
Error:  Loading of version failed for version current
Error:  Unable to build website for locale en.
Error:  Error: Invalid sidebar file at "sidebarsDocsKits.js".
These sidebar document ids do not exist:
- kits/Data Chain Kit/Adoption View
```

→ https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/actions/runs/5998727958/job/16267509507#step:5:13

Cause for this is the change in line 2 in commit 5f5593d (part of #354). In addition the image in [line 129](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/6e4928923ade7b8710e1b575be5f6aebdb202b30/docs-kits/kits/Data%20Chain%20Kit/page_adoption-view.md?plain=1#L129) prevents successfull build:

```shell
Error: Image docs-kits/kits/Data Chain Kit/img.png used in docs-kits/kits/Data Chain Kit/page_adoption-view.md not found.
    at async Promise.all (index 4)
client (webpack 5.75.0) compiled with 1 error
```

Before merging PRs please ensure that website build is successful. You can test this locally by running `npm run docusaurus start`. This will start an development server of docusaurus where you can directly view your changes to the website.

This issue blocks other open PRs (e.g. #359) from beeing published on our website.

Assigned this issue to contributor of PR 354.

**Comment by carslen** [comment]
This bug effects also additional merged PRs since yesterday: [Build and deploy gh pages action](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/actions/workflows/build-and-deploy-gh-pages.yaml)

Please handle this bug with high prio!

@danielmiehle @maximilianong

**Comment by danielmiehle** [comment]
Hi, we are already working on it.

Von: Carsten Lenz ***@***.***>
Antworten an: "eclipse-tractusx/eclipse-tractusx.github.io" ***@***.***>
Datum: Dienstag, 29. August 2023 um 08:59
An: "eclipse-tractusx/eclipse-tractusx.github.io" ***@***.***>
Cc: "Miehle Daniel, MZ-D-4" ***@***.***>, Mention ***@***.***>
Betreff: Re: [eclipse-tractusx/eclipse-tractusx.github.io] PR #354 prevents webseite build (Issue #360)


Sent from outside the BMW organization - be CAUTIOUS, particularly with links and attachments.

Absender außerhalb der BMW Organisation - Bitte VORSICHT beim Öffnen von Links und Anhängen.

________________________________

This bug effects also additional merged PRs since yesterday: Build and deploy gh pages action<https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/actions/workflows/build-and-deploy-gh-pages.yaml>

Please handle this bug with high prio!

@danielmiehle<https://github.com/danielmiehle> @maximilianong<https://github.com/maximilianong>

**Comment by mkanal** [comment]
Should be resolved by https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/361. 
This was merged now to the main after a review.
