### ISSUE TITLE
Blurred images in the PCF Exchange KIT

### ISSUE THREAD

**Issue by mahtufikhsan** [eclipse-tractusx/eclipse-tractusx.github.io#391]
Hello,

Could you please check for the images below in the PCF Exchange KIT? They are really blurred and invisible to understand. Would be great to get the clear images. Thanks!

![image](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/144636024/2794caa4-8798-402a-b3e1-0b9cf715efaa)
![image](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/assets/144636024/644e650f-d4f2-450d-a1d5-5c6c787a560c)

**Comment by danielmiehle** [comment]
@ChristopherWinterZF and @LuisRickert : Can you please take care of this issue? Thanks!

**Comment by mahtufikhsan** [comment]
Hello @ChristopherWinterZF @LuisRickert could you please send me these original images also here once you got them? Thank you!

**Comment by LuisRickert** [comment]
> Hello @ChristopherWinterZF @LuisRickert could you please send me these original images also here once you got them? Thank you!

Hi @mahtufikhsan I got the original Diagrams unfortunately the problem somewhat persists. I assume the reason is the large delta between the original size and the downsized version displayed within the text. I have a Branch with the updated large images. In this updated version you can read the text if you open the image in another tab.
I try to find a solution such that they are readable when they are integrated within the text.

**Comment by mahtufikhsan** [comment]
Many thanks @LuisRickert. Now I can see the text clearly.

**Comment by LuisRickert** [comment]
PR is ready for review -> [PullRequest](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/398)
